# Uncomment the next line to define a global platform for your project
 platform :ios, '13.1'

target 'LoveCoupons' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  #use_frameworks!
  
  pod 'IQKeyboardManagerSwift'
  pod 'SwiftGen'
  pod 'Firebase/Storage'
  pod 'Firebase/Analytics'
  pod 'Firebase/Database'
  pod 'Firebase/Auth'

end
